application: carpoolfinder
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /phonedial.png
  static_files: static/images/phonedial.png
  upload: static/images/phonedial.png

- url: /mapiconmaker.js
  static_files: static/javascript/mapiconmaker.js
  upload: static/javascript/mapiconmaker.js

- url: /add_place.*
  script: maps.py
  login: required

- url: /mapowner.*
  script: maps.py
  login: required

- url: /.*
  script: maps.py
